[workspace]
resolver = "3"
members = ["manager", "src", "task"]
authors = ["Nasar"]
description = "a simple todo list"
categories = ["command-line", "todo"]
license = "MIT"
license-file = "LICENSE"
publish = false
